service: aws-rust
provider:
  name: aws
  runtime: rust
  memorySize: 128
package:
  individually: true
plugins:
  - serverless-rust
functions:
  hello:
    # handler value syntax is `{cargo-package-name}.{bin-name}`
    # or `{cargo-package-name}` for short when you are building a
    # default bin for a given package.
    handler: serverless-aws-rust
    #events:
    #  - schedule: rate(5 minutes)
