service: aws-rust
provider:
  name: aws
  runtime: provided
  memorySize: 128
plugins:
  - serverless-rust
custom:
  rust:
    dockerTag: '0.2.0-rust-1.31.0'
package:
  individually: true
  exclude:
    - ./**
functions:
  hello:
    handler: serverless-aws-rust.handler
    package:
      include:
        - bootstrap
    #events:
    #  - schedule: rate(5 minutes)
